/** Settings are captured before reservation; SQL independently validates their cost. */
export const IMAGE_FLARE = 'gpt-image-2.5-flare';
export const IMAGE_SUNBURST = 'gpt-image-2.5-sunburst';
// Retained for historical metadata and the dormant Google provider adapter.
export const IMAGE_NANO = 'gemini-3.1-flash-image';
export const IMAGE_LITE = 'gemini-3.1-flash-lite-image';
export function isGoogleImage(model: string) { return model === IMAGE_NANO || model === IMAGE_LITE; }

export class ImageModelUnavailableError extends Error {
 constructor() {
  super('This image model is no longer available. Choose GPT 2.5 Flare, Flare HQ, or Sunburst.');
  this.name = 'ImageModelUnavailableError';
 }
}

/** Only the two shipped legacy IDs have a GPT compatibility route, and only
 * after the server has verified Boost/admin tier. No Google provider is used. */
export function assertImageModelReady(model: unknown, tier?: string) {
 if (typeof model === 'string' && model.startsWith('gemini-') &&
   !(isGoogleImage(model) && (tier === 'boost' || tier === 'admin'))) throw new ImageModelUnavailableError();
}

export function imageConfiguration(requested: unknown, quality: unknown, tier: string, size: string) {
 assertImageModelReady(requested, tier);
 const compatibilityAlias = typeof requested === 'string' && isGoogleImage(requested);
 const model = compatibilityAlias ? IMAGE_FLARE : typeof requested === 'string' ? requested : IMAGE_FLARE;
 if (![IMAGE_FLARE, IMAGE_SUNBURST].includes(model)) throw new Error('Unsupported image model');
 if (tier === 'free' && model !== IMAGE_FLARE) throw new Error('Free images use Flare Low. Choose Flare or upgrade to Boost.');
 return { model, quality: compatibilityAlias ? 'medium' : model === IMAGE_FLARE ? (tier === 'free' || quality === 'low' ? 'low' : 'medium') : 'high', size };
}

/** Identity only: preserve hashes generated by installed clients' original
 * server contract. Existing old jobs must be returned unchanged on retry;
 * reservations and provider calls must use the actual GPT config instead. */
export function imageIdentityConfiguration(requested: unknown, actual: { model: string; quality: string; size: string }) {
 return typeof requested === 'string' && isGoogleImage(requested)
  ? { model: requested, quality: 'native', size: '1K' }
  : actual;
}

export async function imageRequestIdentity(key: unknown, input: unknown) {
 if (key !== undefined && (typeof key !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(key))) throw new Error('Invalid image request key');
 const digest = new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(input))));
 return { key: typeof key === 'string' ? key : crypto.randomUUID(), hash: [...digest].map(x => x.toString(16).padStart(2,'0')).join('') };
}
