/**
 * Smart request router for Arc Local.
 * Decides whether a user request should go to the local Gemma model
 * or stay on the cloud (image gen, web search, voice, vision, code, etc).
 */
import { useLocalAIStore } from '@/store/useLocalAIStore';

export type RouteDestination =
  | 'local'           // Local Gemma — plain chat / reasoning / writing
  | 'cloud-chat'      // Cloud Gemini Flash — chat (when local off or unavailable)
  | 'cloud-image'     // Cloud — image generation
  | 'cloud-search'    // Cloud — web search / Perplexity
  | 'cloud-vision'    // Cloud — image analysis
  | 'cloud-voice'     // Cloud — voice mode (Realtime)
  | 'cloud-code';     // Cloud — IDE / code generation

export interface RouteContext {
  forceWebSearch?: boolean;
  forceCanvas?: boolean;
  forceCode?: boolean;
  hasImageAttachment?: boolean;
  isImageGenerationRequest?: boolean;
  isVoiceMode?: boolean;
}

/**
 * Decide where a request should run.
 * Local routing only happens if:
 *   - User has enabled it
 *   - Local model is ready
 *   - Request type is supported locally (no images, no search, no voice, no code)
 */
export function routeRequest(ctx: RouteContext): RouteDestination {
  const { enabled, status } = useLocalAIStore.getState();

  if (ctx.isVoiceMode) return 'cloud-voice';
  if (ctx.isImageGenerationRequest) return 'cloud-image';
  if (ctx.hasImageAttachment) return 'cloud-vision';
  if (ctx.forceWebSearch) return 'cloud-search';
  if (ctx.forceCanvas || ctx.forceCode) return 'cloud-code';

  if (enabled && status === 'ready') return 'local';
  return 'cloud-chat';
}

/** Human-readable label for the source badge */
export function getRouteLabel(route: RouteDestination): { label: string; icon: 'local' | 'cloud'; tooltip: string } {
  switch (route) {
    case 'local':
      return { label: 'Local · Gemma', icon: 'local', tooltip: 'Generated on your device — private and offline.' };
    case 'cloud-chat':
      return { label: 'Cloud · Gemini Flash', icon: 'cloud', tooltip: 'Generated by cloud AI.' };
    case 'cloud-image':
      return { label: 'Cloud · Nano Banana', icon: 'cloud', tooltip: 'Image generation runs in the cloud.' };
    case 'cloud-search':
      return { label: 'Cloud · Perplexity', icon: 'cloud', tooltip: 'Web search requires internet — handled in the cloud.' };
    case 'cloud-vision':
      return { label: 'Cloud · Vision', icon: 'cloud', tooltip: 'Image analysis runs in the cloud.' };
    case 'cloud-voice':
      return { label: 'Cloud · Realtime', icon: 'cloud', tooltip: 'Voice mode requires cloud streaming.' };
    case 'cloud-code':
      return { label: 'Cloud · Gemini Pro', icon: 'cloud', tooltip: 'Code generation uses the most powerful cloud model.' };
  }
}
