-- Historical full-schema import from the Lovable migration. Every table,
-- trigger, policy, and storage bucket in that export is already created by the
-- preceding incremental migrations. Keeping the duplicate as a no-op makes the
-- migration history replayable on a clean Supabase project.
