-- Candidate migration, filename generated by Supabase CLI 2.120.0.
-- This file does not change existing image,
-- research, voice, Flash, subscription or billing functions.
-- All pools start in observation mode. Approved Sol/Astra amounts are staged
-- below; unrelated feature allowance amounts remain unconfigured.

CREATE TABLE public.arc_usage_policy (
  pool text PRIMARY KEY CHECK (pool IN ('luna','sol','astra','research','images','builder_images','background')),
  enforcement_enabled boolean NOT NULL DEFAULT false,
  free_daily_nanos bigint CHECK (free_daily_nanos BETWEEN 0 AND 9007199254740991),
  free_monthly_nanos bigint CHECK (free_monthly_nanos BETWEEN 0 AND 9007199254740991),
  boost_daily_nanos bigint CHECK (boost_daily_nanos BETWEEN 0 AND 9007199254740991),
  boost_monthly_nanos bigint CHECK (boost_monthly_nanos BETWEEN 0 AND 9007199254740991),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (pool <> 'luna' OR NOT enforcement_enabled),
  CHECK (NOT enforcement_enabled OR
    ((free_daily_nanos IS NOT NULL OR free_monthly_nanos IS NOT NULL) AND
     (boost_daily_nanos IS NOT NULL OR boost_monthly_nanos IS NOT NULL)))
);
INSERT INTO public.arc_usage_policy(pool) VALUES
 ('luna'),('sol'),('astra'),('research'),('images'),('builder_images'),('background');
-- Owner-approved Astra amount. Access and enforcement are separate release
-- decisions; this never enables Astra, changes billing, or invents a daily cap.
UPDATE public.arc_usage_policy SET free_monthly_nanos=0,boost_monthly_nanos=3000000000
 WHERE pool='astra';
-- Approved Sol policy. Boost has no additional daily cap.
UPDATE public.arc_usage_policy SET free_daily_nanos=50000000,free_monthly_nanos=1000000000,
 boost_monthly_nanos=6000000000 WHERE pool='sol';

CREATE TABLE public.arc_usage_windows (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pool text NOT NULL REFERENCES public.arc_usage_policy(pool),
  window_kind text NOT NULL CHECK (window_kind IN ('day','month')),
  window_start date NOT NULL,
  spent_nanos bigint NOT NULL DEFAULT 0 CHECK (spent_nanos >= 0),
  reserved_nanos bigint NOT NULL DEFAULT 0 CHECK (reserved_nanos >= 0),
  PRIMARY KEY(user_id,pool,window_kind,window_start)
);
CREATE TABLE public.arc_usage_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pool text NOT NULL REFERENCES public.arc_usage_policy(pool),
  request_key text NOT NULL CHECK (length(request_key) BETWEEN 1 AND 200),
  source text NOT NULL CHECK (length(source) BETWEEN 1 AND 64),
  usage_day date NOT NULL,
  usage_month date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id,pool,request_key)
);
CREATE TABLE public.arc_usage_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL REFERENCES public.arc_usage_requests(id) ON DELETE CASCADE,
  attempt_key text NOT NULL CHECK (length(attempt_key) BETWEEN 1 AND 200),
  model text NOT NULL CHECK (length(model) BETWEEN 1 AND 128),
  fingerprint text NOT NULL CHECK (length(fingerprint) BETWEEN 1 AND 200),
  reserved_ceiling_nanos bigint NOT NULL CHECK (reserved_ceiling_nanos BETWEEN 1 AND 9007199254740991),
  charged_nanos bigint NOT NULL DEFAULT 0 CHECK (charged_nanos >= 0),
  held_nanos bigint NOT NULL CHECK (held_nanos >= 0),
  state text NOT NULL DEFAULT 'reserved' CHECK (state IN ('reserved','provisional','settled')),
  revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(request_id,attempt_key)
);
CREATE INDEX arc_usage_pending_idx ON public.arc_usage_reservations(updated_at,id)
 WHERE state <> 'settled';
CREATE TABLE public.arc_usage_receipts (
  reservation_id uuid NOT NULL REFERENCES public.arc_usage_reservations(id) ON DELETE CASCADE,
  receipt_key text NOT NULL CHECK (length(receipt_key) BETWEEN 1 AND 200),
  action text NOT NULL CHECK (action IN ('checkpoint','final','reconcile')),
  amount_nanos bigint NOT NULL CHECK (amount_nanos BETWEEN 0 AND 9007199254740991),
  detail jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(detail)='object' AND octet_length(detail::text)<=16384),
  revision integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(reservation_id,receipt_key)
);

ALTER TABLE public.arc_usage_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arc_usage_windows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arc_usage_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arc_usage_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arc_usage_receipts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.arc_usage_policy,public.arc_usage_windows,public.arc_usage_requests,
 public.arc_usage_reservations,public.arc_usage_receipts FROM PUBLIC,anon,authenticated,service_role;

-- Internal functions have no direct execution grants. Mutation wrappers below
-- also validate the signed service role; no user metadata is authorization.
CREATE FUNCTION public.arc_usage_require_service() RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
 IF coalesce(auth.jwt()->>'role','') <> 'service_role' THEN
   RAISE EXCEPTION 'Service role required' USING ERRCODE='42501';
 END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.arc_usage_require_service() FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION public.arc_usage_snapshot(target_user_id uuid,pool_name text DEFAULT 'sol')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 p public.arc_usage_policy%ROWTYPE;
 today date := (now() AT TIME ZONE 'UTC')::date;
 month_start date := date_trunc('month',now() AT TIME ZONE 'UTC')::date;
 is_admin boolean;
 tier_name text;
 daily_limit bigint;
 monthly_limit bigint;
 day_spent bigint:=0; day_reserved bigint:=0;
 month_spent bigint:=0; month_reserved bigint:=0;
BEGIN
 SELECT * INTO STRICT p FROM public.arc_usage_policy WHERE pool=pool_name;
 SELECT EXISTS(SELECT 1 FROM public.admin_users WHERE user_id=target_user_id) INTO is_admin;
 tier_name:=CASE WHEN is_admin THEN 'admin' WHEN public.user_has_boost(target_user_id) THEN 'boost' ELSE 'free' END;
 IF p.enforcement_enabled AND NOT is_admin THEN
   daily_limit:=CASE WHEN tier_name='boost' THEN p.boost_daily_nanos ELSE p.free_daily_nanos END;
   monthly_limit:=CASE WHEN tier_name='boost' THEN p.boost_monthly_nanos ELSE p.free_monthly_nanos END;
 END IF;
 SELECT spent_nanos,reserved_nanos INTO day_spent,day_reserved FROM public.arc_usage_windows
  WHERE user_id=target_user_id AND pool=pool_name AND window_kind='day' AND window_start=today;
 SELECT spent_nanos,reserved_nanos INTO month_spent,month_reserved FROM public.arc_usage_windows
  WHERE user_id=target_user_id AND pool=pool_name AND window_kind='month' AND window_start=month_start;
 day_spent:=coalesce(day_spent,0); day_reserved:=coalesce(day_reserved,0);
 month_spent:=coalesce(month_spent,0); month_reserved:=coalesce(month_reserved,0);
 RETURN jsonb_build_object('pool',pool_name,'tier',tier_name,'adminUncapped',is_admin,
  'enforcementEnabled',p.enforcement_enabled,
  'configured',(p.free_daily_nanos IS NOT NULL OR p.free_monthly_nanos IS NOT NULL) AND (p.boost_daily_nanos IS NOT NULL OR p.boost_monthly_nanos IS NOT NULL),
  'daily',jsonb_build_object('spentNanos',day_spent,'reservedNanos',day_reserved,'limitNanos',daily_limit,
    'remainingNanos',CASE WHEN daily_limit IS NULL THEN NULL ELSE greatest(0,daily_limit-day_spent-day_reserved) END,
    'usagePercent',CASE WHEN daily_limit IS NULL THEN NULL WHEN daily_limit=0 THEN 100 ELSE least(100,round(100.0*(day_spent+day_reserved)/daily_limit,2)) END,
    'resetsAt',(today+1)::timestamp AT TIME ZONE 'UTC'),
  'monthly',jsonb_build_object('spentNanos',month_spent,'reservedNanos',month_reserved,'limitNanos',monthly_limit,
    'remainingNanos',CASE WHEN monthly_limit IS NULL THEN NULL ELSE greatest(0,monthly_limit-month_spent-month_reserved) END,
    'usagePercent',CASE WHEN monthly_limit IS NULL THEN NULL WHEN monthly_limit=0 THEN 100 ELSE least(100,round(100.0*(month_spent+month_reserved)/monthly_limit,2)) END,
    'resetsAt',(month_start+interval '1 month')::timestamp AT TIME ZONE 'UTC'));
END;
$$;
REVOKE ALL ON FUNCTION public.arc_usage_snapshot(uuid,text) FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION public.get_my_arc_usage(pool_name text DEFAULT 'sol') RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE caller uuid:=auth.uid();
BEGIN
 IF caller IS NULL THEN RAISE EXCEPTION 'Unauthorized' USING ERRCODE='42501'; END IF;
 RETURN public.arc_usage_snapshot(caller,pool_name);
END;
$$;
REVOKE ALL ON FUNCTION public.get_my_arc_usage(text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_my_arc_usage(text) TO authenticated,service_role;

CREATE FUNCTION public.reserve_arc_usage(
 target_user_id uuid,request_key text,attempt_key text,source_name text,model_name text,
 requested_nanos bigint,request_fingerprint text,pool_name text DEFAULT 'sol',
 minimum_nanos bigint DEFAULT 1,clamp_to_remaining boolean DEFAULT false
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 p public.arc_usage_policy%ROWTYPE;
 r public.arc_usage_requests%ROWTYPE;
 a public.arc_usage_reservations%ROWTYPE;
 has_request boolean; has_attempt boolean; bypass boolean;
 today date:=(now() AT TIME ZONE 'UTC')::date;
 month_start date:=date_trunc('month',now() AT TIME ZONE 'UTC')::date;
 daily_limit bigint; monthly_limit bigint;
 day_total bigint:=0; month_total bigint:=0;
 available bigint:=9007199254740991;
 ceiling bigint; old_allocation bigint:=0; old_hold bigint:=0; new_hold bigint;
BEGIN
 PERFORM public.arc_usage_require_service();
 IF target_user_id IS NULL OR request_key IS NULL OR length(request_key) NOT BETWEEN 1 AND 200
  OR attempt_key IS NULL OR length(attempt_key) NOT BETWEEN 1 AND 200
  OR source_name IS NULL OR length(source_name) NOT BETWEEN 1 AND 64
  OR model_name IS NULL OR length(model_name) NOT BETWEEN 1 AND 128
  OR request_fingerprint IS NULL OR length(request_fingerprint) NOT BETWEEN 1 AND 200
  OR requested_nanos IS NULL OR requested_nanos NOT BETWEEN 1 AND 9007199254740991
  OR minimum_nanos IS NULL OR minimum_nanos NOT BETWEEN 1 AND requested_nanos
  OR clamp_to_remaining IS NULL THEN RAISE EXCEPTION 'Invalid usage reservation'; END IF;
 IF (model_name='gpt-6-luna' AND pool_name<>'luna')
  OR (model_name='gpt-6.1-sol' AND pool_name<>'sol')
  OR (model_name='gpt-6-astra' AND pool_name<>'astra') THEN
  RAISE EXCEPTION 'Model usage pool mismatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM auth.users WHERE id=target_user_id AND NOT coalesce(is_anonymous,false)) THEN
  RAISE EXCEPTION 'Signed-in account required' USING ERRCODE='42501'; END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(target_user_id::text||':'||coalesce(pool_name,''),7831));
 SELECT * INTO STRICT p FROM public.arc_usage_policy WHERE pool=pool_name FOR SHARE;
 SELECT * INTO r FROM public.arc_usage_requests q
  WHERE q.user_id=target_user_id AND q.pool=pool_name AND q.request_key=reserve_arc_usage.request_key;
 has_request:=FOUND;
 IF has_request THEN
  IF r.source<>source_name THEN RAISE EXCEPTION 'Usage request identity conflict'; END IF;
  today:=r.usage_day; month_start:=r.usage_month;
  SELECT * INTO a FROM public.arc_usage_reservations x WHERE x.request_id=r.id AND x.attempt_key=reserve_arc_usage.attempt_key FOR UPDATE;
  has_attempt:=FOUND;
 ELSE has_attempt:=false; END IF;
 IF has_attempt THEN
  IF a.model<>model_name OR a.fingerprint<>request_fingerprint THEN RAISE EXCEPTION 'Usage attempt identity conflict'; END IF;
  IF a.state='settled' OR a.reserved_ceiling_nanos>=requested_nanos THEN
   RETURN public.arc_usage_snapshot(target_user_id,pool_name)||jsonb_build_object('allowed',true,'replayed',true,
    'reservationId',a.id,'reservedNanos',a.reserved_ceiling_nanos,'providerBudgetCents',a.reserved_ceiling_nanos/10000000,
    'state',a.state,'revision',a.revision,'cumulativeCostNanos',a.charged_nanos);
  END IF;
  old_hold:=a.held_nanos; old_allocation:=a.charged_nanos+a.held_nanos;
 END IF;
 SELECT EXISTS(SELECT 1 FROM public.admin_users WHERE user_id=target_user_id) INTO bypass;
 bypass:=bypass OR NOT p.enforcement_enabled;
 IF NOT bypass THEN
  IF public.user_has_boost(target_user_id) THEN daily_limit:=p.boost_daily_nanos; monthly_limit:=p.boost_monthly_nanos;
  ELSE daily_limit:=p.free_daily_nanos; monthly_limit:=p.free_monthly_nanos; END IF;
  SELECT spent_nanos+reserved_nanos INTO day_total FROM public.arc_usage_windows
   WHERE user_id=target_user_id AND pool=pool_name AND window_kind='day' AND window_start=today;
  SELECT spent_nanos+reserved_nanos INTO month_total FROM public.arc_usage_windows
   WHERE user_id=target_user_id AND pool=pool_name AND window_kind='month' AND window_start=month_start;
  available:=greatest(0,least(coalesce(daily_limit-coalesce(day_total,0)+old_allocation,9007199254740991),
    coalesce(monthly_limit-coalesce(month_total,0)+old_allocation,9007199254740991)));
 END IF;
 ceiling:=CASE WHEN clamp_to_remaining THEN least(requested_nanos,available) ELSE requested_nanos END;
 IF ceiling<minimum_nanos OR ceiling>available OR (has_attempt AND ceiling<a.reserved_ceiling_nanos) THEN
  RETURN public.arc_usage_snapshot(target_user_id,pool_name)||jsonb_build_object('allowed',false,'replayed',has_attempt,
    'reservationId',CASE WHEN has_attempt THEN a.id ELSE NULL END,'reservedNanos',0,'providerBudgetCents',0,
    'cumulativeCostNanos',coalesce(a.charged_nanos,0),'reason','usage_limit');
 END IF;
 IF NOT has_request THEN
  INSERT INTO public.arc_usage_requests(user_id,pool,request_key,source,usage_day,usage_month)
   VALUES(target_user_id,pool_name,reserve_arc_usage.request_key,source_name,today,month_start) RETURNING * INTO r;
 END IF;
 new_hold:=greatest(0,ceiling-coalesce(a.charged_nanos,0));
 IF has_attempt THEN
  UPDATE public.arc_usage_reservations SET reserved_ceiling_nanos=ceiling,held_nanos=new_hold,
   revision=revision+1,updated_at=now() WHERE id=a.id RETURNING * INTO a;
 ELSE
  INSERT INTO public.arc_usage_reservations(request_id,attempt_key,model,fingerprint,reserved_ceiling_nanos,held_nanos)
   VALUES(r.id,reserve_arc_usage.attempt_key,model_name,request_fingerprint,ceiling,new_hold) RETURNING * INTO a;
 END IF;
 INSERT INTO public.arc_usage_windows(user_id,pool,window_kind,window_start,reserved_nanos)
  VALUES(target_user_id,pool_name,'day',today,new_hold-old_hold),(target_user_id,pool_name,'month',month_start,new_hold-old_hold)
  ON CONFLICT(user_id,pool,window_kind,window_start) DO UPDATE
   SET reserved_nanos=public.arc_usage_windows.reserved_nanos+EXCLUDED.reserved_nanos;
 RETURN public.arc_usage_snapshot(target_user_id,pool_name)||jsonb_build_object('allowed',true,'replayed',has_attempt,
  'reservationId',a.id,'reservedNanos',a.reserved_ceiling_nanos,'providerBudgetCents',a.reserved_ceiling_nanos/10000000,
  'state',a.state,'revision',a.revision,'cumulativeCostNanos',a.charged_nanos);
END;
$$;
REVOKE ALL ON FUNCTION public.reserve_arc_usage(uuid,text,text,text,text,bigint,text,text,bigint,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_arc_usage(uuid,text,text,text,text,bigint,text,text,bigint,boolean) TO service_role;

CREATE FUNCTION public.record_arc_usage(
 target_user_id uuid,reservation_id uuid,receipt_key text,cumulative_nanos bigint,is_final boolean,
 usage_detail jsonb DEFAULT '{}'
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 r public.arc_usage_requests%ROWTYPE; a public.arc_usage_reservations%ROWTYPE;
 receipt public.arc_usage_receipts%ROWTYPE;
 action_name text:=CASE WHEN is_final THEN 'final' ELSE 'checkpoint' END;
 new_charge bigint; new_hold bigint;
BEGIN
 PERFORM public.arc_usage_require_service();
 IF receipt_key IS NULL OR length(receipt_key) NOT BETWEEN 1 AND 200 OR cumulative_nanos IS NULL
  OR cumulative_nanos NOT BETWEEN 0 AND 9007199254740991 OR is_final IS NULL
  OR usage_detail IS NULL OR jsonb_typeof(usage_detail)<>'object' OR octet_length(usage_detail::text)>16384
  THEN RAISE EXCEPTION 'Invalid usage receipt'; END IF;
 SELECT q.* INTO r FROM public.arc_usage_requests q JOIN public.arc_usage_reservations x ON x.request_id=q.id
  WHERE x.id=reservation_id AND q.user_id=target_user_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Usage reservation unavailable' USING ERRCODE='42501'; END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(target_user_id::text||':'||r.pool,7831));
 SELECT * INTO STRICT a FROM public.arc_usage_reservations WHERE id=reservation_id FOR UPDATE;
 SELECT * INTO receipt FROM public.arc_usage_receipts x WHERE x.reservation_id=record_arc_usage.reservation_id AND x.receipt_key=record_arc_usage.receipt_key;
 IF FOUND THEN
  IF receipt.action<>action_name OR receipt.amount_nanos<>cumulative_nanos OR receipt.detail<>usage_detail THEN
   RAISE EXCEPTION 'Usage receipt identity conflict'; END IF;
  RETURN public.arc_usage_snapshot(target_user_id,r.pool)||jsonb_build_object('revision',a.revision,'cumulativeCostNanos',a.charged_nanos,'replayed',true);
 END IF;
 IF a.state='settled' THEN
  IF is_final AND a.charged_nanos<>cumulative_nanos THEN RAISE EXCEPTION 'Use reconciliation for a settled usage amount'; END IF;
  RETURN public.arc_usage_snapshot(target_user_id,r.pool)||jsonb_build_object('revision',a.revision,'cumulativeCostNanos',a.charged_nanos,'replayed',true,'ignored',true);
 END IF;
 new_charge:=CASE WHEN is_final THEN cumulative_nanos ELSE greatest(a.charged_nanos,cumulative_nanos) END;
 new_hold:=CASE WHEN is_final THEN 0 ELSE greatest(0,a.reserved_ceiling_nanos-new_charge) END;
 UPDATE public.arc_usage_windows SET spent_nanos=spent_nanos+new_charge-a.charged_nanos,
  reserved_nanos=reserved_nanos+new_hold-a.held_nanos
  WHERE user_id=target_user_id AND pool=r.pool AND
   ((window_kind='day' AND window_start=r.usage_day) OR (window_kind='month' AND window_start=r.usage_month));
 UPDATE public.arc_usage_reservations SET charged_nanos=new_charge,held_nanos=new_hold,
  state=CASE WHEN is_final THEN 'settled' ELSE 'provisional' END,revision=revision+1,updated_at=now()
  WHERE id=reservation_id RETURNING * INTO a;
 INSERT INTO public.arc_usage_receipts(reservation_id,receipt_key,action,amount_nanos,detail,revision)
  VALUES(reservation_id,receipt_key,action_name,cumulative_nanos,usage_detail,a.revision);
 RETURN public.arc_usage_snapshot(target_user_id,r.pool)||jsonb_build_object('revision',a.revision,'cumulativeCostNanos',a.charged_nanos,'replayed',false);
END;
$$;
REVOKE ALL ON FUNCTION public.record_arc_usage(uuid,uuid,text,bigint,boolean,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.record_arc_usage(uuid,uuid,text,bigint,boolean,jsonb) TO service_role;

CREATE FUNCTION public.reconcile_arc_usage(
 target_user_id uuid,reservation_id uuid,receipt_key text,expected_revision integer,
 authoritative_nanos bigint,usage_detail jsonb
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 r public.arc_usage_requests%ROWTYPE; a public.arc_usage_reservations%ROWTYPE;
 receipt public.arc_usage_receipts%ROWTYPE;
BEGIN
 PERFORM public.arc_usage_require_service();
 IF receipt_key IS NULL OR length(receipt_key) NOT BETWEEN 1 AND 200 OR authoritative_nanos IS NULL
  OR authoritative_nanos NOT BETWEEN 0 AND 9007199254740991 OR expected_revision IS NULL OR expected_revision<0
  OR usage_detail IS NULL OR jsonb_typeof(usage_detail)<>'object' OR octet_length(usage_detail::text)>16384
  OR length(coalesce(usage_detail->>'reason','')) NOT BETWEEN 1 AND 500 THEN RAISE EXCEPTION 'Invalid reconciliation'; END IF;
 SELECT q.* INTO r FROM public.arc_usage_requests q JOIN public.arc_usage_reservations x ON x.request_id=q.id
  WHERE x.id=reservation_id AND q.user_id=target_user_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Usage reservation unavailable' USING ERRCODE='42501'; END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(target_user_id::text||':'||r.pool,7831));
 SELECT * INTO STRICT a FROM public.arc_usage_reservations WHERE id=reservation_id FOR UPDATE;
 SELECT * INTO receipt FROM public.arc_usage_receipts x WHERE x.reservation_id=reconcile_arc_usage.reservation_id AND x.receipt_key=reconcile_arc_usage.receipt_key;
 IF FOUND THEN
  IF receipt.action<>'reconcile' OR receipt.amount_nanos<>authoritative_nanos OR receipt.detail<>usage_detail THEN
   RAISE EXCEPTION 'Usage receipt identity conflict'; END IF;
  RETURN public.arc_usage_snapshot(target_user_id,r.pool)||jsonb_build_object('revision',a.revision,'cumulativeCostNanos',a.charged_nanos,'replayed',true);
 END IF;
 IF a.state<>'settled' OR a.revision<>expected_revision THEN RAISE EXCEPTION 'Usage reconciliation revision conflict'; END IF;
 UPDATE public.arc_usage_windows SET spent_nanos=spent_nanos+authoritative_nanos-a.charged_nanos
  WHERE user_id=target_user_id AND pool=r.pool AND
   ((window_kind='day' AND window_start=r.usage_day) OR (window_kind='month' AND window_start=r.usage_month));
 UPDATE public.arc_usage_reservations SET charged_nanos=authoritative_nanos,revision=revision+1,updated_at=now()
  WHERE id=reservation_id RETURNING * INTO a;
 INSERT INTO public.arc_usage_receipts(reservation_id,receipt_key,action,amount_nanos,detail,revision)
  VALUES(reservation_id,receipt_key,'reconcile',authoritative_nanos,usage_detail,a.revision);
 RETURN public.arc_usage_snapshot(target_user_id,r.pool)||jsonb_build_object('revision',a.revision,'cumulativeCostNanos',a.charged_nanos,'replayed',false);
END;
$$;
REVOKE ALL ON FUNCTION public.reconcile_arc_usage(uuid,uuid,text,integer,bigint,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reconcile_arc_usage(uuid,uuid,text,integer,bigint,jsonb) TO service_role;

COMMENT ON TABLE public.arc_usage_policy IS 'Observation-only until explicit approved per-pool allowances and enforcement are configured. No billing changes.';
COMMENT ON TABLE public.arc_usage_reservations IS 'One provider attempt/session per logical request. Unknown provider outcomes retain their hold; no automatic timeout refund.';
